- <b>Conference Reviewer</b> - IJCNN 2025, AAIM 2025, CSoNet 2024, AAIM2024, COCOON2024 
- <b>Journal Reviewer</b> - IEEE Transactions on Neural Networks and Learning Systems, Journal of Combinatorial Optimization.
- <b>ACM Member.</a>  </b> 
- <b>AAAS Member.</b>
